### ISSUE TITLE
Wrong path in shared.scss

### ISSUE THREAD

**Issue by MathiasGmeiner** [k-next/ui#16]
If I try to run `npm run dev` or `npm start --sync` or a similar command I get a lot of `File to import not found or unreadable` errors.

If I **change line 9** in **shared.scss** from `@import 'styles/z-index.scss';` to `@import 'z-index.scss';` everything works fine.

**Comment by bastianallgeier** [comment]
That's so weird. Why would it run fine for us and break for you? I'm not an expert with npm in general, but maybe @nocksock has an idea?

**Comment by bastianallgeier** [comment]
You should start it btw: with `npm run start` only.

**Comment by pedroborges** [comment]
I was getting the same error messages. The fix suggested by @MathiasGmeiner did it for me.

**Comment by distantnative** [comment]
After a re-install, I got the same errors, fix worked as well.

**Comment by bnomei** [comment]
i guess `@import` is using `url()`to resolve the relative path and thus is relative to the file calling the `@import` rule.

https://developer.mozilla.org/en-US/docs/Web/CSS/url

**Comment by krisak** [comment]
Sass @import extends css @import so it works in similar relative way. If you put url() or http path or .css sass will leave it as css @import. If you put filename it will try to find it and compile i don't think there is any concept of root though so ```@import 'styles/z-index.scss';``` or even ```@import 'styles/z-index.scss';``` won't work unless you change the structure.

I think proper sass way would actually be 
```@import 'z-index';```
