### ISSUE TITLE
UI i18n

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/ui#54]
We need translations for the interface and it would be great if we could reuse some of the stuff from Kirby 2. There has been so much effort going into translating Kirby that it would be a shame to just throw it all away. So we should try to convert most of the translation strings in a good clean way. We also need a system to include those translations in Vue. Is there a good lib we can use or should we roll our own?

**Comment by distantnative** [comment]
Had a first look at http://kazupon.github.io/vue-i18n/en/ and it looks good for giving it a try. We sould figure out how to connect it to Transifex.

**Comment by bastianallgeier** [comment]
@distantnative looks really nice indeed! Transifex stores json files anyway, so this should be pretty simple to include.

**Comment by distantnative** [comment]
@bastianallgeier I guess it more comes down to figure out what we can reuse from the old Transifex and what new strings we would need.

**Comment by distantnative** [comment]
I haven't found a way to rename Transifex translation keys, which would be good to take them over to v3. Anyone knows if this is possible?

https://docs.transifex.com/projects/updating-content/#what-happens-when-you-update-files
